services:
  discord-bot:
    container_name: crafty-discord-bot
    build: .
    restart: unless-stopped
    image: crafty-discord-bot:latest

    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=32

    deploy:
      resources:
        limits:
          memory: 50M

    env_file:
      - .env

    mem_limit: 50m

    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3
